FROM ubuntu:20.04

RUN apt-get update 
RUN apt-get -y install wget
RUN apt-get -y install python
RUN wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl

EXPOSE 80

WORKDIR /home/user
